Algoritmo "ler3Numerors"
Var
N1, N2, N3, Maior: Inteiro
Procedimento Maior ()
Inicio
Se (N1 > N2) e (N1 > N3) entao
Escreva (N1," é o maior valor. ")
FimSe
Se (N2 > N1) e (N2 > N3) entao
Escreva (N2," é o maior valor. ")
FimSe
Se (N3 > N1) e (N3 > N2) entao
Escreva (N3," é o maior valor. ")
FimSe
 FimProcedimento
Inicio
Escreva ("Informe o primeiro numero: ")
Leia (N1)
Escreva ("Informe o segundo numero: ")
Leia (N2)
Escreva ("Informe o terceiro numero: ")
Leia (N3)
Maior ()
Fimalgoritmo